# generated by datamodel-codegen:
#   filename:  extraction_review.schema.json
#   timestamp: 2026-09-18T15:29:12+00:00

from __future__ import annotations
from enum import Enum
from uuid import UUID
from typing import Annotated
from pydantic import AwareDatetime, BaseModel, Field


class FlaggedReason(Enum):
    low_confidence = 'low_confidence'
    conflicting_extractions = 'conflicting_extractions'
    validation_failed = 'validation_failed'
    illegible = 'illegible'
    manual_flag = 'manual_flag'
    extraction_failed = 'extraction_failed'


class Status(Enum):
    pending = 'pending'
    resolved = 'resolved'
    rejected = 'rejected'


class ExtractionReview(BaseModel):
    id: UUID
    receipt_id: UUID
    line_item_id: Annotated[
        UUID | None,
        Field(
            description="Set when the issue belongs to a specific line item. Null for receipt-level fields and for 'missing_line_item' and 'receipt' reviews."
        ),
    ] = None
    field_name: Annotated[
        str,
        Field(
            description="Either an actual field name (e.g. 'total', 'quantity', 'staff_name'), or one of three sentinel values: 'line_item' (the row itself is wrong — merged, split, or invented), 'missing_line_item' (an item was missed entirely), or 'receipt' (extraction failed for the whole receipt — no candidate data at all; paired with flagged_reason='extraction_failed')."
        ),
    ]
    extractor_source: Annotated[
        str,
        Field(
            description="Which agent/model produced this candidate value, e.g. 'claude-vision-v2', 'tesseract-ocr'. For 'receipt'-scoped total-failure reviews, identifies which extractor failed."
        ),
    ]
    extracted_value: Annotated[
        str | None,
        Field(
            description="What the extractor produced. Null for 'missing_line_item' and 'receipt', since nothing was extracted."
        ),
    ] = None
    confidence_score: Annotated[float, Field(ge=0.0, le=1.0)]
    flagged_reason: Annotated[
        FlaggedReason,
        Field(
            description="'extraction_failed' means the extractor produced no usable candidate at all for the receipt (unreadable image, vendor API error, etc.) — always paired with field_name='receipt'. The others all describe qualifying an actual candidate value."
        ),
    ]
    extractor_notes: str | None = None
    status: Annotated[
        Status,
        Field(
            description="'rejected' is reversible — it means unresolved at this time, not permanently unrecoverable, and can move to 'resolved' later."
        ),
    ]
    reviewed_value: Annotated[
        str | None,
        Field(
            description="For a single-field issue: the corrected value. For field_name='line_item': a full corrected line, or the literal string 'delete'. For field_name='missing_line_item': the full item to add. For field_name='receipt': the full corrected receipt data, once available (e.g. from a re-scan or manual entry)."
        ),
    ] = None
    resolution_notes: str | None = None
    reviewed_by: str | None = None
    created_at: AwareDatetime | None = None
    resolved_at: AwareDatetime | None = None
