# generated by datamodel-codegen:
#   filename:  line_item.schema.json
#   timestamp: 2026-09-18T15:29:12+00:00

from __future__ import annotations
from uuid import UUID
from pydantic import BaseModel


class LineItem(BaseModel):
    id: UUID
    receipt_id: UUID
    description: str
    quantity: float
    unit_price: float
    line_total: float
    line_order: int
