# generated by datamodel-codegen:
#   filename:  receipt.schema.json
#   timestamp: 2026-09-18T13:43:16+00:00

from __future__ import annotations
from uuid import UUID
from datetime import date as date_aliased, time as time_aliased
from typing import Annotated, Any
from pydantic import BaseModel, Field
from . import line_item_schema


class Receipt(BaseModel):
    id: UUID
    store_id: UUID
    source_image_id: str
    transaction_ref: str
    transaction_ref_label: str | None = None
    register_ref: str | None = None
    date: date_aliased
    time: time_aliased | None = None
    staff_name: str | None = None
    customer_name: str | None = None
    payment_method: str | None = None
    subtotal: float | None = None
    discount: float | None = None
    vat: float | None = None
    consumption_tax: float | None = None
    total: float
    total_in_words: str | None = None
    content_hash: Annotated[
        str,
        Field(
            description='Fingerprint of key receipt fields, unique per receipt. Guards against the same physical receipt being ingested twice (e.g. re-photographed).'
        ),
    ]
    extras: Annotated[
        dict[str, Any] | None,
        Field(
            description='Store-specific or one-off fields not promoted to a dedicated column: barcode/QR presence, website, items-count line, promotional or return-policy footer text, secondary reference numbers, etc.'
        ),
    ] = None
    line_items: list[line_item_schema.LineItem] | None = None
