# generated by datamodel-codegen:
#   filename:  store.schema.json
#   timestamp: 2026-09-14T19:07:59+00:00

from __future__ import annotations
from uuid import UUID
from pydantic import AwareDatetime, BaseModel, Field


class Store(BaseModel):
    id: UUID
    name: str = Field(
        ...,
        description='Together with address, unique per store — guards against the same physical store being recorded twice as separate rows.',
    )
    address: str = Field(
        ...,
        description='Together with name, unique per store. Two branches of the same chain at different addresses remain distinct rows.',
    )
    phone: str | None = None
    email: str | None = None
    website: str | None = None
    created_at: AwareDatetime | None = None
