# generated by datamodel-codegen:
#   filename:  store.schema.json
#   timestamp: 2026-09-13T19:28:02+00:00

from __future__ import annotations
from uuid import UUID
from pydantic import AwareDatetime, BaseModel


class Store(BaseModel):
    id: UUID
    name: str
    address: str
    phone: str | None = None
    email: str | None = None
    website: str | None = None
    created_at: AwareDatetime | None = None
